---
title: "Graphe_et_traitement_de_donnees"
author: "Rémi Legrand"
date: "12/01/2022"
output: 
  html_document :
    toc: true # table of content true
    toc_float: True
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
---

# Importation des packages necessaires et des données

```{r message=FALSE, warning=FALSE}
library(reshape)
library(ROBITools2) #analyse des données métabarcoding
library(ggplot2) #affichage graphique avancé
library(dplyr) #pour manipuler les données
library(tidyr) #idem
library(stringr) #pour manipuler les chaînes de caractères
library(openxlsx) #pour manipuler les fichiers .xlsx
library(igraph)
```

```{r}
motus2 <- read.table("motus_afrique_sud_remi2.txt")
data2 <- read.table("data_afrique_sud_remi2.txt")
samples2 <- read.table("samples_afrique_sud_remi2.txt")
reference <- read.xlsx("Plant reference collection sequence information.xlsx", 
                       sheet = 2)
View(reference)
```

# Rédaction de fonction pour le traitement des distances entre les motus


## fonction pour calculer la matrice de distance
```{r}
matrice_distance <- function(sequence, seuil) {
  sequence_bis <- sequence[sequence$count > seuil,]
  x <- sapply(sequence_bis$sequence[1:nrow(sequence_bis)], lcs_score, sequence_bis$sequence[1:nrow(sequence_bis)], similarity_mode = "distance")
  matrice_dist <- matrix(unlist(x), nrow = length(sequence_bis$sequence[1:nrow(sequence_bis)]), ncol = length(sequence_bis$sequence[1:nrow(sequence_bis)]), byrow = T)
  return(matrice_dist)
}

```

## Fonction pour savoir si l'espèce est dans la ref

```{r}
dans_ref <- function(base_donnee, ref){
  base_donnee[,"dans_ref"] <- F
  for (c in 1:nrow(base_donnee)) {
    if (base_donnee$sequence[c] %in% ref$Sequence.ID) {
      base_donnee$dans_ref[c] <- T
      return(base_donnee)
    }
  } 
}

a <- dans_ref(motus2, reference)
View(a)
```



```{r}
matrice_adjacence <- function(matrice_distance, seuil_lien){
  for (i in 1:nrow(motus2bis)) {
    if (motus2bis$dans_ref[i] == T) {
      matrice_adj2[i,] <- 0 # n'est lié à rien d'autre
    }else {
      if (1 %in% matrice_distance2[i,1:(i-1)]) {
        a <- which(matrice_distance2[i,1:(i-1)] == 1)
        if (length(a) == 1) {
          matrice_adj2[i,] <- 0
          matrice_adj2[i,a] <- 1 # se rattache à cette espèce
        }else {
          matrice_adj2[i,] <- 0
          matrice_adj2[i,a] <- 1 # lié aux deux mais perte de l'info de la répartition entre les deux
        }
      }else{
        matrice_adj2[i,] <- 0 # définition d'une probable nouvelle espèce
      }
    }
  }
}
```



```{r}
matrice_adj2 <- matrix(data = NA, nrow = nrow(motus2bis), ncol = nrow(motus2bis))

couleur <- NULL
for (i in 1:nrow(motus2bis)) {
  if (motus2bis$dans_ref[i] == T) {
    matrice_adj2[i,] <- 0 # n'est lié à rien d'autre
    # couleur <- rbind(couleur, "green")
  }else {
    if (1 %in% matrice_distance2[i,1:(i-1)]) {
      a <- which(matrice_distance2[i,1:(i-1)] == 1)
      # print(length(a))
      if (length(a) == 1) {
        matrice_adj2[i,] <- 0
        matrice_adj2[i,a] <- 1 # se rattache à cette espèce
        # couleur <- rbind(couleur, "yellow")
      }else {
        matrice_adj2[i,] <- 0
        matrice_adj2[i,a] <- 1 # lié aux deux mais perte de l'info de la répartition entre les deux
        # couleur <- rbind(couleur, "yellow")
      }
    }else{
      matrice_adj2[i,] <- 0 # définition d'une probable nouvelle espèce
      # couleur <- rbind(couleur, "red")
    }
  }
}

taille_vertex <- 3*log10(motus2bis$count)

graph_liens <- graph_from_adjacency_matrix(matrice_adj2[1:nrow(motus2bis),1:nrow(motus2bis)])
# V(graph_liens)$color <- couleur
V(graph_liens)$size <- taille_vertex

tkplot(graph_liens, mode='directed')

View(matrice_adj2)
```














